version: "3"

services:
  control-node:
    build: .
    container_name: ansible-control
    volumes:
      - ./ansible:/ansible
    networks:
      - ansible-net
    command: ["tail", "-f", "/dev/null"]

  node1:
    image: ubuntu:22.04
    container_name: node1
    networks:
      - ansible-net
    command: ["/bin/bash", "-c", "apt update && apt install -y openssh-server && mkdir -p /var/run/sshd && echo 'root:root' | chpasswd && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && service ssh start && tail -f /dev/null"]


  node2:
    image: ubuntu:22.04
    container_name: node2
    networks:
      - ansible-net
    command: ["/bin/bash", "-c", "apt update && apt install -y openssh-server && mkdir -p /var/run/sshd && echo 'root:root' | chpasswd && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && service ssh start && tail -f /dev/null"]

networks:
  ansible-net:
